version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - make install
  build:
    commands:
      - set -eu
      - env | grep REACT
      - yarn run build
      - yarn run deploy
